[package]
name = "subotai"
version = "0.1.0"
authors = ["Cu3rv0 <pablomansanet@gmail.com>"]

[dependencies]
itertools = "*"
rand = "*"
bincode = "*"
serde = "*"
serde_macros = "*"
bus = "*"
time = "*"
log = "*"
log4rs = "*"
